FROM node:22-alpine

# Install necessary build tools
RUN apk add --no-cache python3 make g++

# Set npm registry argument
ARG NPM_REGISTRY=https://registry.npmjs.org

# Set npm registry
RUN npm config set registry $NPM_REGISTRY

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install -g npm@latest
RUN npm install

# Explicitly install CSS-related dependencies
RUN npm install --save-dev autoprefixer postcss tailwindcss

# Copy the rest of the application
COPY . .

# Expose port
EXPOSE 3000

# Start the application in development mode with webpack
CMD ["npx", "next", "dev"]
